app/__init__.py
from flask import Flask

import mysql.connector 


#db = list()
db = mysql.connector.connect( 
    host ='informatica.iesquevedo.es',
    port = 3333,
    user ='root', 
    password ='1asir', 
    database='rober'
) 



def create_app():
    app = Flask(__name__)
    app.debug = True
    

    

    from .routes import routes

    app.register_blueprint(routes.rutas_usuarios)

    return app

app/routes/routes.py
from flask import Blueprint, render_template, request,  redirect, url_for
from app.data.jugadores_dao import Jugadores_dao

from app import db
rutas_usuarios = Blueprint("routes", __name__)

@rutas_usuarios.route("/")
def index():
    return render_template("index.html")

@rutas_usuarios.route("/formulario")
def formulario():
    return render_template("formulario.html")

#SELECT DE LOS JUGADORES
@rutas_usuarios.route("/datos")
def datos():
    jugadores_dao = Jugadores_dao()
    jugadores = jugadores_dao.select_all(db)
    return render_template("datos.html", jugadores=jugadores)




#INSERTAR JUGADORES:
@rutas_usuarios.route('/formulario_jugador', methods=['POST'])
def formulario_jugador():
    nombre_jugador = request.form['nombre_jugador'] 
    superviviente_favorito = request.form['superviviente_favorito'] 
    asesino_favorito = request.form['asesino_favorito']

    if (nombre_jugador and superviviente_favorito and asesino_favorito):
        cursor = db.cursor()  
        sql = "INSERT INTO Jugadores (Nombre_Jugador,id_superviviente_favorito,id_asesino_favorito) VALUES (%s, %s, %s)" 
        data = (nombre_jugador,superviviente_favorito,asesino_favorito) 
        cursor.execute(sql,data) 
        db.commit()
    return redirect(url_for('routes.formulario'))

#ELIMINAR JUGADORES
@rutas_usuarios.route("/borrar_datos", methods=['POST'])
def delete():
    id = request.form['id'] 
    cursor = db.cursor() 
    sql = "DELETE FROM Jugadores WHERE id=%s"
    data = list()
    data.append(id)  
    cursor.execute(sql,data) 
    db.commit()
    return redirect(url_for('routes.datos')) 



    
    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <title>{% block title %}Aitana{% endblock %}</title>
    
    {% endblock %}
    
    
</head>
<body>
    <h1>
        FORMULARIO DEAD BY DAYLIGHT  
    </h1>
    <form class="centra">
		Nombre del jugador:<input type="name" maxlength="15"> <br>
        Rol favorito<br>
<input type="radio" name="Sexo">Asesino<br>
<input type="radio" name="Sexo">Superviviente<br>
		Fecha de inicio en el juego <input type="date" name="in"><br>
		Asesino favorito:<input type="name" maxlength="15"> <br>
        Superviviente favorito:<input type="name" maxlength="15"> <br>
Cosas que te gusten mucho del juego <input type=""><br>
<input type="submit"><input type="reset">

	</form>
        
        
        
    
    <div id="content">{% block content %}{% endblock %}</div>
    <div id="footer">
        {% block footer %}
        
        {% endblock %}
    </div>
</body>
</html>

app/templates/datos.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
        <title>{% block title %}Datos{% endblock %}</title>
        
        {% endblock %}
        
        
    </head>
<body class="fondo">
    <div class="centra">
    <h1>Datos del formulario</h1>
    <a href="{{ url_for('routes.index') }}">Página principal</a> 
    <a href="{{ url_for('routes.formulario') }}">Formulario</a></div><br>
    <table  border class="tabla">
        <tr>
            <th>ID del jugador</th>
            <th>Jugador</th>
            <th>Superviviente favorito</th>
            <th>Asesino favorito</th>
        </tr>
    {% for jugador in jugadores %}
        <tr>
            <td>{{ jugador.id }}</td>
            <td>{{ jugador.Nombre_Jugador }}</td>
            <td>{{ jugador.Nombre_Superviviente }}</td>
            <td>{{ jugador.Nombre_Asesino }}</td>
        </tr>
    {% endfor %}</table>
    <table>
        <tr>
            <td>ID del jugador que quieres eliminar<form class="centra" action="/borrar_datos" method="post"><input type="text" name="id"><input type="submit"></form></td>
        </tr>
    </table>
</body>

app/templates/formulario.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <title>{% block title %}Formulario{% endblock %}</title>
    
    {% endblock %}
    
    
</head>
<body>
    <h1 class="centra">
        FORMULARIO DEAD BY DAYLIGHT 
    </h1>
    <form class="centra" action="/formulario_jugador" method="post">
		Nombre del jugador:<input type="text", name="nombre_jugador" maxlength="15"> <br>
        <p>Nombre de tu superviviente favorito <br>
			<select name="superviviente_favorito">
				<option value="1">Ada Wong</option>
				<option value="2">Felix Richter</option>
			</select>
		</p>
        <p>Nombre de tu asesino favorito <br>
			<select name="asesino_favorito">
				<option value="1">La cazadora</option>
				<option value="2">El oni</option>
			</select>
		</p>
<input type="submit"><input type="reset"> <br>
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
<h1 class="centra"><img src="{{ url_for('static', filename='imagenes/ada.jpg') }}"></h1><br>
<a href="{{ url_for('routes.index') }}">Página principal</a>
<a href="{{ url_for('routes.datos') }}">Datos</a> <br>


	</form>
        
        
        
    
    <div id="content">{% block content %}{% endblock %}</div>
    <div id="footer">
        {% block footer %}
        
        {% endblock %}
    </div>
    
</body>
</html>

app/templates/index.html
<title>{% block title %}Dead by Daylight{% endblock %}</title>



{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    
    <h1 class="centra">PÁGINA DEAD BY DAYLIGHT</h1>
    <div class="centra">
      <img src="{{ url_for('static', filename='imagenes/steve.jpg') }}">
    </div>
    <div class="centra">
    <a href="{{ url_for('routes.formulario') }}">Formulario</a> 
    <a href="{{ url_for('routes.datos') }}">Datos</a> <br>
    </div>
    
    
    
{% endblock %}

app/templates/supervivientes.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <title>{% block title %}Formulario{% endblock %}</title>
    
    {% endblock %}
    
    
</head>
<body>
    <h1 class="centra">
        FORMULARIO SUPERVIVIENTES  
    </h1>
    <form class="centra" action="/formulario_supervivientes" method="post">
		Nombre del jugador:<input type="text", name="nombre_jugador" maxlength="15"> <br>
        <p>Nombre de tu superviviente favorito <br>
			<select name="superviviente_favorito">
				<option value="nea">Nea Karlsson</option>
				<option value="ada">Ada Wong</option>
			</select>
		</p>
		Color de pelo:<input type="text", name="color_de_pelo" maxlength="15"> <br>
        <p>Nombre de tu asesino favorito <br>
			<select name="asesino">
				<option value="cazadora">La cazadora</option>
				<option value="payaso">El payaso</option>
			</select>
		</p>
		<p>Metros por segundo <br>
			<select name="metros_por_segundo">
				<option value="3.8">3.8</option>
				<option value="4.4">4.4</option>
                <option value="4.6">4.6</option>
			</select> <br><br>
<input type="submit"><input type="reset"> <br>
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
<h1 class="centra"><img src="{{ url_for('static', filename='imagenes/ada.jpg') }}"></h1><br>
<a href="{{ url_for('routes.index') }}">Página principal</a>


	</form>
        
        
        
    
    <div id="content">{% block content %}{% endblock %}</div>
    <div id="footer">
        {% block footer %}
        
        {% endblock %}
    </div>
    
</body>
</html>